const jokes = [
  {
    category: "Programming",
    type: "twopart",
    setup: "Programming is like sex.",
    delivery:
      "Make one mistake and you end up supporting it for the rest of your life.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 8,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why are Assembly programmers always soaking wet?",
    delivery: "They work below C-level.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 264,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 123,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the database administrator leave his wife?",
    delivery: "She had one-to-many relationships.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 265,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 55,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What is the most used language in programming?",
    delivery: "Profanity.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 193,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why do programmers wear glasses?",
    delivery: "Because they need to C#",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 50,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "Why did the JavaScript heap close shop?",
    delivery: "It ran out of memory.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 31,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'Two SQL tables sit at the bar. A query approaches and asks "Can I join you?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 221,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "twopart",
    setup: "What is a dying programmer's last program?",
    delivery: "Goodbye, world!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 56,
    safe: true,
    lang: "en",
  },
];


for(i=0; i<jokes.length; i++){
  console.log(`${jokes[i].category},
  ${jokes[i].type},
  ${jokes[i].setup},
  ${jokes[i].joke},
  ${jokes[i].delivery},
  ${jokes[i].flags.nsfw},
  ${jokes[i].flags.religious},
  ${jokes[i].flags.political},
  ${jokes[i].flags.racist},
  ${jokes[i].flags.sexist},
  ${jokes[i].flags.explicit},
  ${jokes[i].id},
  ${jokes[i].safe},
  ${jokes[i].lang},`);
}